name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cache Maven Repo
        id: cache-maven-repo
        uses: actions/cache@v1
        with:
          path: /home/runner/.m2/repository
          key: ${{ runner.os }}-maven-repo
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Release
        run: mvn -B release:prepare release:perform


